### ISSUE TITLE
1.2 Windows release fails on Windows 10?

### ISSUE THREAD

**Issue by warrenmcquinn** [Washington-University/workbench#14]
Hi,

Thank you for this excellent software. I'm trying to run wb_view.exe of the 1.2.0 release on my Windows 10 laptop, and I'm getting this error:

![wb_view](https://cloud.githubusercontent.com/assets/1995151/15587742/71fe0a7c-233f-11e6-83a9-1146216d4a71.PNG)

Can anyone help me figure out how to build this software for my version of Win10?

**Comment by coalsont** [comment]
That was our mistake, a mismatch between our build and release environments, please use this one instead for now:

http://brainvis.wustl.edu/workbench/workbench-windows64-v1.2.0.zip

We'll update the zip on our main site soon.

It is also possible to build it yourself, but not as easy on windows, as you need several other libraries first (QT, freetype).  See the readme in the source root: https://github.com/Washington-University/workbench/blob/master/README
