### ISSUE TITLE
Workbench Tutorial Data

### ISSUE THREAD

**Issue by akkashyap** [Washington-University/workbench#16]
Hey HCP, this might not be the correct place to post this, but I have been using the rsfMRI data provided by the HCP workbench tutorial in scene 4 (CP10101). It looks like there has been some preprocessing done to the rsfMRI dtseries but I am not sure what it is. My own analysis techniques seem to work pretty well on this processed data but perform pretty poorly on the raw data. Is there any documentation/paper you could direct me to.
Thanks
Amrit

**Comment by glasserm** [comment]
I would use the publicly available main HCP data release, rather than the tutorial data.

**Comment by akkashyap** [comment]
I downloaded the publicly available data and attempted to run it on that, but it just didn't work as well. So I am curious what is so special about the tutorial data. It was posted for the tutorial because the preprocessing does an good job on it. (I am guessing that it was spatially smoothed but there is no way from my end that I can verify that).

**Comment by glasserm** [comment]
These questions are probably best addressed on the HCP Users mailing list, as this is really a software bugs and patches reporting system.
