### ISSUE TITLE
is it Qt5 fully compatible?

### ISSUE THREAD

**Issue by yarikoptic** [Washington-University/workbench#18]
in light of https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=784458
Qt4's WebKit removal

thought to build against Qt5 but decided to check first

**Comment by coalsont** [comment]
No idea, and probably no time to test until next week.  You could try using the QT4/QT5 pattern from CiftiLib's CMakeLists.txt, if you really wanted to.

**Comment by coalsont** [comment]
Looks like we need to update QuaZIP before cmake will be happy with Qt5, and then we can see where compilation goes.  In sid it doesn't seem to ship with a cmake file to find it, so workbench won't just take a system version currently.

As for webkit specifically, I don't know that we use it currently (we did at one point).  We may be able to drop it from the cmake scripts.

**Comment by coalsont** [comment]
Actually, the only references I currently see to webkit are commented out.  Can you test packaging it without a webkit dependency, and see if everything works?

**Comment by johnvelab** [comment]
[cid:7007180A-BD30-449A-A742-33D509A8F6F5]
On Sep 6, 2016, at 8:04 PM, Tim Coalson <notifications@github.com<mailto:notifications@github.com>> wrote:


Actually, the only references I currently see to webkit are commented out. Can you test packaging it without a webkit dependency, and see if everything works?

**Comment by johnvelab** [comment]
Tried to send an image earlier today so that is why an empty reply was received.

From June 9, 2016, commit a318f3b5d504:

Disabled usage of Qt's Webkit because: (1) While there is code that uses webkit, it is disabled; (2) I have unable to build Qt 4.8.6 with webkit enabled on the new supercomputer cluster and on winbuild; and (3) WebKit will be removed and replaced in the soon to be released Qt 5.7.

**Comment by coalsont** [comment]
The current master (and therefore next release, whenever that will be) builds against qt5 (set cmake variable WORKBENCH_USE_QT5 to "true"), closing this issue.
