### ISSUE TITLE
how to smooth data end with .shape.gii

### ISSUE THREAD

**Issue by xiaoqiC** [Washington-University/workbench#23]
hello~
    I am a graduate in UCAS in China. I got some problems in processing the HCP S900 data. 
    I try to smooth the data such as thickness, sulc, curvatue and so on(file end with shape.gii), but I find that in workbench, the command 'wb_command -surface-smoothing' cannot smoothing the data directly, it can only smooth the file end with surf.gii.  I want to know is there any command that i do not know to smooth the data, or there exist other way to smooth this kind of data?

    thank you in advance for help

**Comment by coalsont** [comment]
Use wb_command -metric-smoothing.

For general help questions, see the hcp-users list or our contact form:

http://www.humanconnectome.org/contact/

For finding what is available in wb_command, see wb_command -list-commands, or this page:

http://www.humanconnectome.org/software/workbench-command.php?function=-list-commands

You may also want to read wb_command -gifti-help to explain what .shape.gii files are:

http://www.humanconnectome.org/software/workbench-command.php?function=-gifti-help
