### ISSUE TITLE
feature-request: Command-line interface to wb_view

### ISSUE THREAD

**Issue by AnonymousBoba** [Washington-University/workbench#30]
Are there any plans to implement a command-line interface to wb_view (something similar to those in FSLeyes and freeview)? This seems somewhat common in software of this class and might be useful to automate production of figures.

**Comment by johnvelab** [comment]
There is a command line program, wb_command, that comes with wb_view.  wb_command contains a ‘-show-scene’ command that generates an image from a wb_view scene file.  A scene file must be created in wb_view.  Some users use a stream editor, such as ’sed’ to adapt the scene file (for example, change data file names within the scene file) for use with other datasets.


On Mar 28, 2019, at 1:23 PM, AnonymousBoba <notifications@github.com<mailto:notifications@github.com>> wrote:


Are there any plans to implement a command-line interface to wb_view (something similar to those in FSLeyes and freeview)? This seems somewhat common in software of this class and might be useful to automate production of figures.

**Comment by coalsont** [comment]
wb_view does take a list of filenames to load, and uses some simple logic to open the types of tabs that can view the loaded files, and set a few default layers.  I don't think we have discussed making more advanced options to expose display options to the command line.

As John mentioned, if what you want to do is reproduce a particular view setup on different data, our approach is to save the view setup into an "scene file" (which is XML), and then edit the paths in that file (mostly to replace subject IDs) to work for different data with the same types of files.  There are a large number of options to change how something is displayed in wb_view, so it would be difficult to make command line options as powerful as scene files.

**Comment by AnonymousBoba** [comment]
Thank you, that makes sense and seems like a viable alternative to a command-line interface.
