### ISSUE TITLE
ZLIB_1.2.9 not found

### ISSUE THREAD

**Issue by alexsayal** [Washington-University/workbench#35]
Hello,
When starting wb_view I get the following error:

`<path>/workbench/bin_linux64/../exe_linux64/wb_view: <path>/workbench/bin_linux64/../libs_linux64/libz.so.1: version `ZLIB_1.2.9' not found (required by /usr/lib/x86_64-linux-gnu/libpng16.so.16)
<path>/workbench/bin_linux64/../exe_linux64/wb_view: <path>/workbench/bin_linux64/../libs_linux64/libz.so.1: version `ZLIB_1.2.3.4' not found (required by /usr/lib/x86_64-linux-gnu/libpng16.so.16)`

I have seen some hints online but I would like to know what is the correct way to fix this.

Thank you in advance!

**Comment by glasserm** [comment]
What OS is this?

**Comment by alexsayal** [comment]
Sorry, I am on Ubuntu 18.04

**Comment by johnvelab** [comment]
Please see: https://www.mail-archive.com/hcp-users@humanconnectome.org/msg07348.html

John H

On Oct 28, 2019, at 8:32 AM, Alexandre Sayal <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry, I am on Ubuntu 18.04

**Comment by alexsayal** [comment]
Ok, renaming the libz.so.1 file worked fine.

Thank you!
