### ISSUE TITLE
Could it do a parcellation work?

### ISSUE THREAD

**Issue by Irismoon** [Washington-University/workbench#36]
Hi, 
Thanks for your work.
I'm unsure if this is the right place to ask question. But I find no forum on the webpage. I'm a newbie to MRI data. And my aim is to acquire the parcellation of MRI data I have. I know freesurfer could do this, but it only provide very rough desikan and another atlas whose number of parcellated areas is too few for me. I hope I could get output as the fine parcellation including AIP, PF, etc. when I provide my data input as T1 data. 
I'm unsure if I rpovide enough information for u to understand. Let me know if anything unclear.

Best,
Mangp

**Comment by glasserm** [comment]
The HCP's parcellation is available here: https://balsa.wustl.edu/file/show/3VLx

**Comment by Irismoon** [comment]
> The HCP's parcellation is available here: https://balsa.wustl.edu/file/show/3VLx

Hi, Thanks for reply. I checked the link but it seems not exactly what I want. What I would like is HCP could provide a file like lh.hcp.gcs, and I could then use mri_ca_label, etc to generate the .annot file for the parcellation. Do you know its existence or any similar pipeline which could generate an .annot file from my subject's label and surf file? Really appreciate your reply.

Best,
Mango

**Comment by coalsont** [comment]
This kind of data, usage and cross-software question is better asked on a mailing list like hcp-users, sign up at the lower right of this page: https://www.humanconnectome.org/contact-us

You can use `wb_command -cifti-separate` to write out single-hemisphere gifti .label.gii files, which freesurfer should accept in `mris_convert --annot`.

**Comment by Irismoon** [comment]
> This kind of data, usage and cross-software question is better asked on a mailing list like hcp-users, sign up at the lower right of this page: https://www.humanconnectome.org/contact-us
> 
> You can use `wb_command -cifti-separate` to create single-hemisphere gifti .label.gii files from our cifti-format parcellation, which freesurfer should accept in `mris_convert --annot`.

Hi, Thanks. This is very helpful. But I'm wondering if your cifti-format parcellation is a common template or not. Because I need to get the .annot file for each of my subjects. I guess I need a individualized .annot file. How can I get it? Or do you know if there is a tutorial for that. 
Thanks again!
Best,
Mango

**Comment by Irismoon** [comment]
> This kind of data, usage and cross-software question is better asked on a mailing list like hcp-users, sign up at the lower right of this page: https://www.humanconnectome.org/contact-us
> 
> You can use `wb_command -cifti-separate` to create single-hemisphere gifti .label.gii files from our cifti-format parcellation, which freesurfer should accept in `mris_convert --annot`.

Hi, after I subscribe to the mail list, I didn't receive any ensuing contact. So I will try to post my new question here and hopefully receive the feedback.

I’m referring to the tutorial here https://wiki.humanconnectome.org/display/PublicData/HCP+Users+FAQ#HCPUsersFAQ-9.HowdoImapdatabetweenFreeSurferandHCP?  the (C) option to map the HCP parcellation(Q1-Q6_RelatedValidation210.CorticalAreas_dil_Final_Final_Areas_Group_Colors.32k_fs_LR.dlabel.nii) to my subject’s surface data processed by freesurfer. The case is I have reconstructed my subject's data in freesurfer, but I want to use the parcellation atlas of HCP. So I process this as the following procedures:
1) wb_command -cifti-separate xxx.dlabel.nii …..: to convert the hcp nii file into fs_LR.label..gii file which is still under fs_LR template
2) wb_command -label-resample …….: to convert the fs_LR.label.gii file into fsaverage.label.gii under fsaverage template;
3) mris_convert —annot fsaverage.label.gii hcp.fsaverage.label.annot: to acquire the annot file under fsaverage template

So my question is: 
(a) In step (3), the syntax of mris_convert from freesurfer help is: mris_convert —annot lh.aparc.gii lh.white.gii lh.aparc.annot, but I don’t have the similar white.gii file from HCP.
(b)what should I do next? how can I convert the hcp.fsaverage.label.annot to label my subject’s surface? I think of using mris_ca_train to create .gcs file and mris_ca_label to create the individual.annot file as https://surfer.nmr.mgh.harvard.edu/fswiki/CorticalParcellation, but the concern is: to create .gcs file, mris_ca_train <canonsurf> <annotfile> <subject1> [subject2] <outputfile>, I think these input should come from the HCP subjects’ data. But now I only have that for annotfile. So how can I acquire other files? Or there is other ways I could get the .gcs file of the HCP Atalas.

Best,
Mango

**Comment by coalsont** [comment]
Please give the mailing list at least a day, preferably until a workday has passed, to give a response to your question.  Also, the process of signing up for the mailing list currently requires some manual steps on our end.

**Comment by Irismoon** [comment]
> Please give the mailing list at least a day, preferably until a workday has passed, to give a response to your question. Also, the process of signing up for the mailing list currently requires some manual steps on our end.

Thanks! I got reply!:)
