### ISSUE TITLE
Issue using `wb_command -convert-warpfield`

### ISSUE THREAD

**Issue by andrewtmorgan** [Washington-University/workbench#37]
I am trying to use `workbench` to convert warpfields from `FSL` to `ITK` so that I can use `FSL`'s distortion correction in `ANTs`. However, I am running into an issue where `antsApplyTransforms` does not apply the warpfield and I am wondering if this issue is coming from the conversion of the field.

Here is the example code:

```bash
wb_command -convert-warpfield \
    -from-fnirt warpfield_fromtopup.nii.gz test_im.nii.gz \
    -to-itk warpfield_fromtopup_itk.nii.gz

antsApplyTransforms \
    -d 3 \
    -i test_im.nii.gz \
    -o warped_im.nii.gz \
    -n BSpline \
    -t warpfield_fromtopup_itk.nii.gz \
    -r test_im.nii.gz \
    -v 1
```

`antsApplyTransforms` does not show anything going wrong in its output, but `test_im.nii.gz` and `warped_im.nii.gz` are identical. I have never had any issues with `antsApplyTransforms` when I use warpfields created from `antsRegistration`. 

I was excited when I recently found this feature in `workbench`, but now I am confused about whether the conversion is working properly. Are there any suggestions for how to pinpoint the problem?

**Comment by coalsont** [comment]
You can load the warpfield as a volume file in wb_view, and check that it
overlaps the data file, and also that it has some structure at the cortex,
where the registration should be doing something.  We might have to ask itk
or ants people about their format, maybe they embed a units identifier
somewhere.

Tim

**Comment by andrewtmorgan** [comment]
Okay, I found a solution for the issue (although it is not very clean). The problem stemmed from `FSL` storing warp dimensions as volumes while `ITK` stores them as channels.

Step 1: I added the affine information to the warpfield because `FSL` does not add it by default and `workbench` seems to need it. I did this with `nibabel`, but I think it could just as well be done with `fslcpgeom`:

```python
import nibabel as nb

warp = nb.load('warpfield.nii.gz')
data = img.get_fdata()

func = nb.load('func.nii.gz')

img = nb.Nifti1Image(data, func.affine)
img.to_filename('warpfield_edit.nii.gz')
```

Step 2: I used `workbench` to convert the warpfield to `ITK` format:

```bash
wb_command -convert-warpfield \
   -from-fnirt warpfield_edit.nii.gz func.nii.gz \
   -to-itk warpfield_edit2.nii.gz
```

Step 3: After the warpfield is in `ITK` format, the warp maps need to be moved from volumes (dim 3) to channels (dim 4) and the header needs to be edited:

```python
def wb2itk(warpname, funcname): 
   import numpy as np 
   import nibabel as nb 

   warp = nb.load(warpname) 
   func = nb.load(funcname) 
   data = warp.get_fdata()                # warp data is size [x, y, z, 3]
   data = np.expand_dims(data, 3)  # makes the new warp size [x, y, z, 1, 3]

   # new nifti
   img = nb.Nifti1Image(data, func.affine) 
   
   # change header
   hdr = img.header 
   hdr.set_intent('vector') 
   hdr['xyzt_units'] = 2 
   hdr['pixdim'][-4:] = 0.0 
   hdr['pixdim'][0] = -1 
   hdr['qform_code'] = 1 
   hdr['regular'] = 'r' 
   img.set_sform(np.zeros((4,4)), 0) 

   return img

img = wb2itk('warpfield_edit2.nii.gz', 'func.nii.gz')
img.to_filename('warpfield_itk.nii.gz')
```

After these steps, `warpfield_itk.nii.gz` can be used with `antsApplyTransforms` or `greedy`. I tried to do this in fewer steps by changing the header prior to converting the warpfield with `workbench`, but `workbench` actually changes the warpfield data back to the size used by `FSL`. 

It makes sense that `workbench` needs the affine information that I add in Step 1 (after all, the `ITK` format is in real space, so you cannot go into it without knowing where you are starting). However, it would be helpful for the `workbench` call to also do the equivalent of what I have done in Step 3 since this seems to be a requirement for `ITK` programs.

Best,
Tyler

**Comment by coalsont** [comment]
Thanks for chasing down these details, it is very helpful.  I'll see about
having wb_command do more about dealing with them.

Tim

**Comment by coalsont** [comment]
```
hdr['xyzt_units'] = 2
hdr['pixdim'][-4:] = 0.0
```

Are these lines absolutely necessary for itk to recognize the file as a warpfield?  Internally, workbench sets the XYZT units when the spacing info (sform) is set, so overriding that would need a bit of a hack.  We also fill unused pixdim elements with 1s simply because other nifti readers aren't very careful.

```
hdr['pixdim'][0] = -1
hdr['qform_code'] = 1
...
img.set_sform(np.zeros((4,4)), 0)
```

Why are you messing with the qform and sform?  Once they are matched to the proper image space, they should not need modification, and pixdim[0] encodes the handedness of the image (which nifti interprets as whether to do a z-flip before the quaternion rotation), so whether these lines do the right thing will likely depend on the details of the input files...

`hdr['regular'] = 'r'`

This is marked as unused in nifti-1, only analyze programs (which don't handle one-file nifti anyway) should need it set to 'r'.  Hopefully ANTS/ITK doesn't need this set, but this could be added to our header initialization easily enough.

**Comment by andrewtmorgan** [comment]
Thanks for your message. You are right, the following lines were not required:

```python
hdr['xyzt_units'] = 2  
hdr['pixdim'][-4:] = 0.0  
hdr['pixdim'][0] = -1  
hdr['qform_code'] = 1  
hdr['regular'] = 'r'  
img.set_sform(np.zeros((4,4)), 0)  
```

The reason I had set those parameters initially was just for safety. I ran a registration with `ANTS` and compared the headers from the `FSL`- and `ANTS`-produced warpfields. I then changed everything in the `FSL` header to make it look like the one from `ANTS`, but clearly this was overkill. I removed the lines above and the warpfield still seems to work fine in both `ANTS` and `ITK`/`greedy`.

I also just tested whether the other two lines were absolutely necessary:

```python
data = np.expand_dims(data, 3)
# and
hdr.set_intent('vector')
```

and found that yes, both of these attributes of the warpfields need to be changed for `ANTS` to read them correctly. I think that narrows down the process to just making sure the warpfield's intent is marked as 'vector' and that the vector components are stored as channels (not volumes).

Thanks very much for your help with this!

**Comment by coalsont** [comment]
It is a little worrying that ants/itk doesn't seem to care if the warpfield's sform is z-flipped compared to what should be spatially correct...

I have made those two changes to the header of itk warpfields that wb_command writes.  Please try the appropriate dev_latest zip file from here:

http://brainvis.wustl.edu/workbench/

Note that this is only for testing, we do not recommend using a non-released version for ordinary tasks, especially for making scene files in wb_view, as we may make and/or revert changes to scenes that are incompatible with any released version of workbench.
