### ISSUE TITLE
Movie recording unable to save video

### ISSUE THREAD

**Issue by AdebayoBraimah** [Washington-University/workbench#38]
Hi,

I am currently running into an issue in which every time I attempt to record and save a movie via `wb_view`, I am met with a file not found error. I am on MacOS X Mojave, running version 1.4.1 of Connectome Workbench.

I was wondering if this issue had occurred before. If so - is there a solution? 

Best,

![Screen Shot 2020-02-10 at 6 14 32 PM](https://user-images.githubusercontent.com/30060496/74199209-8b283d00-4c31-11ea-8fa4-8df4601dbabb.png)

**Comment by johnvelab** [comment]
We have not seen this problem before.

Were images recorded prior to the attempt to create a movie?  Are there any image files (name begins with “movie”) in the directory that begins with /var/folders ?  Note that “movie%06d.png” is a pattern to match the recorded “png” images.

John

**Comment by AdebayoBraimah** [comment]
Hi Jon,

Thanks for getting back to me.

As far as images being recorded, I believe so. I began by setting the recording mode to automatic 
and collected 30 frames (attached).

I do not see any files that begin with "movie" in their filenames in the `/var/folders` directory.

Best, 

![Screen Shot 2020-02-11 at 12 46 31 PM](https://user-images.githubusercontent.com/30060496/74263310-895f8780-4ccc-11ea-947c-04f275717818.png)

**Comment by AdebayoBraimah** [comment]
Hi Jon,

I just found the problem.

The recording mode should have been `Manual` rather than `Automatic`.

I just tried it, and it works.

Thanks!

Closing this issue.
