### ISSUE TITLE
Install workbench on Suse Linux

### ISSUE THREAD

**Issue by stephanwu89** [Washington-University/workbench#40]
Hi,

is it possible to install workbench on Suse Linux?

Best,
Steph

**Comment by johnvelab** [comment]
We have distributions for both CentOS/RedHat and Ubuntu/Debian.  One or both of them should run on Suse Linux (maybe RedHat is more appropriate for Suse?).

The workbench distributions are downloaded from https://www.humanconnectome.org/software/get-connectome-workbench

John Harwell
