### ISSUE TITLE
HCP installation on Mac Catalina

### ISSUE THREAD

**Issue by renxili** [Washington-University/workbench#41]
Hi:

I am trying to install HCP on my Mac, and I have entered the following commands in terminal, would you mind looking at what might go wrong?

```
(base) Renxis-Mac-mini:~ renxili$ printenv SHELL
/bin/bash
(base) Renxis-Mac-mini:~ renxili$ cd /Users/renxili/
(base) Renxis-Mac-mini:~ renxili$ echo 'export PATH=$PATH:/Applications/workbench/bin_macosx64' >> ~/.bashrc
(base) Renxis-Mac-mini:~ renxili$ echo 'set PATH = ($PATH   /Applications/workbench/bin_macosx64)' >> ~/.cshrc
(base) Renxis-Mac-mini:~ renxili$ wb_command -file-info
-bash: wb_command: command not found
(base) Renxis-Mac-mini:~ renxili$ 
```

Best,
Renxi

**Comment by johnvelab** [comment]
It looks like the “~” (tilde) is missing before “/.bashrc”.  Try: echo 'export PATH=$PATH:/Applications/workbench/bin_macosx64'  >>  ~/.bashrc

The above command will update the .bashrc file but it will not take effect until a new terminal window is opened (or in the current terminal you could run “source  ~/.bashrc”).

John Harwell

**Comment by renxili** [comment]
Thank you for your reply! I have try the following command, but the terminal still cannot find wb?command:

(base) Renxis-Mac-mini:~ renxili$ cd /Users/renxili/
(base) Renxis-Mac-mini:~ renxili$ echo 'export PATH=$PATH:/Applications/workbench/bin_macosx64'  >>  ~/.bashrc
(base) Renxis-Mac-mini:~ renxili$ echo 'set PATH = ($PATH   /Applications/workbench/bin_linux64)' >> ~/.cshrc
(base) Renxis-Mac-mini:~ renxili$ wb_command
-bash: wb_command: command not found
(base) Renxis-Mac-mini:~ renxili$

**Comment by renxili** [comment]
I think GitHub changes my scripts when posting. Let me attach a screen shoot.
<img width="563" alt="Screen Shot 2020-04-13 at 3 24 19 PM" src="https://user-images.githubusercontent.com/63210044/79157860-f2ca4800-7d9a-11ea-843c-cbcbce9a19f2.png">

**Comment by coalsont** [comment]
Github's markdown formatting got applied to your text and ate all the "~" characters, I will fix it with "preformatted" sections.

Adding the lines to your shell startup file doesn't change your active terminal.  You need to open a new terminal window and try the command there.

By the way, the full command is "wb_command -file-information", the "-file-info" bit is from the optional tab completion instructions, which will not work by default on mac (you must use a newer version of bash than Apple provides to have the prerequisites for our tab completion).

**Comment by coalsont** [comment]
Note that the `echo` lines *append to* files that your shell executes when it starts up, and it looks like you may have executed them more than once.  You may want to use a text editor to make sure `~/.bashrc` and `~/.cshrc` don't contain repeated lines.

**Comment by renxili** [comment]
Do you mean deleting the ">>" before the ~/.bashrc and ~/.cshrc?

**Comment by coalsont** [comment]
No.  Do `nano -w ~/.bashrc` (the -w disables auto line wrapping), use the down arrow key or page down key to get to the bottom of the file, and see if there are multiple lines that say the same thing.  Use the arrow keys to put the cursor on one of the duplicate lines, use control-k to delete the line the cursor is on, until there is only one of the line that was duplicated.  If you mess up, press control-x to quit, and press `n` to not save the changes.  Once you have fixed it correctly, press control-o to save, press enter to accept saving to the same filename, then press control-x to quit (these commands are shown in the bottom of the editor screen, `^` means control).  Do the same for `~/.cshrc`.

You could try textedit, but you would need to be very careful to use plain text mode, not introduce any unicode characters, and you might need to disable autocorrect - if the file is saved with problems in it, new terminal windows will complain and may not have the correct `PATH` and may behave strangely.  If you know someone who uses linux or the command line a lot, you might ask them to help you.

**Comment by renxili** [comment]
I have deleted the duplicated file in both ~/.bashrc and ~/.cshrc. I also updated the bash to 5.0 via homebrew. However, when I put wb_command -file-info in a new terminal, it still says wb_command is not found. Any suggestions?

**Comment by glasserm** [comment]
what is your env

**Comment by coalsont** [comment]
You mean the duplicate lines in `~/.bashrc` and `~/.cshrc`, and not deleting files, right?

Do `echo $PATH` in a new terminal window and tell us what it says.  It is possible that bash is only reading .profile or .bash_profile, and that it doesn't source .bashrc - shell startup is always an adventure.

**Comment by renxili** [comment]
This is when I entered echo $PATH:

(base) Renxis-Mac-mini:~ renxili$ echo $PATH
/Library/Frameworks/Python.framework/Versions/3.8/bin:/Users/renxili/opt/anaconda3/bin:/Users/renxili/opt/anaconda3/condabin:/usr/local/fsl/bin:/anaconda3/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
(base) Renxis-Mac-mini:~ renxili$

**Comment by renxili** [comment]
This is when I entered "printenv SHELL"

(base) Renxis-Mac-mini:~ renxili$ printenv SHELL
/bin/bash

**Comment by renxili** [comment]
Yes, I only delete the duplicate lines in ~/.bashrc and ~/.cshrc, and leaving one line for each ~/.bashrc and ~/.cshrc

**Comment by coalsont** [comment]
Do `cat ~/.bashrc`, `cat ~/.bash_profile` and `cat ~/.profile` and tell us what they say.

**Comment by renxili** [comment]
<img width="1227" alt="Screen Shot 2020-04-13 at 4 42 40 PM" src="https://user-images.githubusercontent.com/63210044/79164036-cff16100-7da5-11ea-956d-fe3d8b8be77a.png">

**Comment by johnvelab** [comment]
On my Mac, I have note to put PATH settings in :.bash_profile”.


Alternatively, adding “if [ -f ~/.bashrc ]; then . ~/.bashrc; fi “ at the beginning of .bash_profile may also solve the problem (see https://apple.stackexchange.com/questions/119711/why-doesnt-mac-os-x-source-bashrc)

**Comment by coalsont** [comment]
So, it looks like for other software you have been putting the lines in your `.bash_profile`.  You also have a line for MSM in your .bashrc, which probably also doesn't work.  I would probably solve this by making the .bash_profile source the .bashrc (like it often does on linux), by doing `echo 'if [[ -f ~/.bashrc ]]; then source ~/.bashrc; fi' >> ~/.bash_profile` (only once!).  John's solution is similar, but uses old sh syntax.

Then, open a new terminal and try `wb_command`.

Our README.txt in the workbench zip distribution looks like it already says to do `echo 'export PATH=$PATH:/Applications/workbench/bin_macosx64' >> ~/.bash_profile`, not .bashrc, so you apparently followed instructions for a different OS?

**Comment by renxili** [comment]
I can get wb_command running under bash 5.0 now! Is wb_command only runnable under bash?

**Comment by coalsont** [comment]
No, wb_command can be run by literally anything that wants to.  The only thing specific to bash is the tab completion of wb_command operations, options, and file extension filtering.  Other shells may still do naive filename tab completion.

**Comment by renxili** [comment]
Okay, now it works in zsh as well. Thank you all so much for your patience and help! You guys are amazing!
