### ISSUE TITLE
Displaying borders substantially slows down loading time in wb_view

### ISSUE THREAD

**Issue by jielisaji** [Washington-University/workbench#44]
Hello,
Starting somewhat recently (maybe in the last 6 months) we've noticed that when borders files are displayed in our scene files, it substantially slows down the loading time in wb_view (e.g. for the Information window to display when clicking on a vertex). If borders are turned off (but still loaded), wb_view speeds up again. This wasn't an issue when we first set up the scene file. We were wondering what may have caused this decrease in loading speed (possibly in the 1.3.2 versus 1.0.0 version of Workbench?).

I am on a Mac running wb_view version 1.3.2. The borders files we are using are "Q1-Q6_RelatedValidation210.L.CorticalAreas_dil_Final_Final_Areas_Group.32k_fs_LR.border" and
"Q1-Q6_RelatedValidation210.R.CorticalAreas_dil_Final_Final_Areas_Group.32k_fs_LR.border", i.e. the 360 cortical parcels from the Multi-Modal Parcellation. With smaller border files that have fewer borders, the loading time is not as slow.

**Comment by glasserm** [comment]
Can you post a scene file to balsa.wustl.edu so we can debug this? You can upload the scene file and associated data from within Connectome Workbench.  You can call the study "Border Slowness Debugging" and it obviously wouldn't be planned to be publicly shared.

**Comment by jielisaji** [comment]
Hi Matt,
Thank you! The scene I am uploading is a copy of one from our publicly-available network partition. Since we are disseminating this scene we are particularly interested in optimizing its performance on wb_view.

**Comment by johnvelab** [comment]
Hello,

One of the border drawing modes (Polylines) can be slow.  In Feature Toolbox -> Borders, there is a selection titled “Draw As”.  If it is Polylines, try switching to Lines.

You might also try the current release of Workbench (1.4.2).  1.3.2 was released about two years ago.

John Harwell

**Comment by jielisaji** [comment]
Switching to Lines does speed it up considerably (we had been using Spheres). Thank you!!
