### ISSUE TITLE
New bugfix release

### ISSUE THREAD

**Issue by y0ast** [Washington-University/workbench#47]
Would it be possible to release a 1.4.3 version that includes https://github.com/Washington-University/workbench/commit/ac5fcb7b05f7733ec59397a11c2545d7ea0fb289 ?

Currently I can't build the release using the latest Qt5 (Qt 5.15.2), which breaks the Arch AUR package: https://aur.archlinux.org/packages/connectome-workbench/

I'm hesitant to use master since >500 commits were made!

**Comment by johnvelab** [comment]
Hello,

We are releasing a new version of Workbench next week and it includes that commit.

John Harwell

**Comment by y0ast** [comment]
Excellent news, thank you!
