### ISSUE TITLE
ffmpeg has "/" hard coded in path

### ISSUE THREAD

**Issue by smazurchuk** [Washington-University/workbench#48]
Hi. This is pretty minor, but the movie recording utility doesn't work by default in windows. The reason is because while workbench ships with a copy of ffmpeg, the path should have a back-slash instead of a hard-coded forward slash

https://github.com/Washington-University/workbench/blob/69b9c4cc740f80f602b66f2b729d6d0d4e026e11/src/Brain/MovieRecorder.cxx#L538-L540

Error generated when creating movie:
![image](https://user-images.githubusercontent.com/29523859/113147350-4fb24e80-91f6-11eb-91b9-0cc617d8cc12.png)

**Comment by johnvelab** [comment]
I have pushed out an update that replaces several instances of forward slashes with QDir::separator().  I am still working remotely and since I do not have access to a Windows computer, I am unable to verify that the update corrects the problem.

**Comment by smazurchuk** [comment]
Awesome! Since I don't build from source, I can't verify it either! But thanks for the quick reply and fix!! 

Just a quick side-note. I also actually did set the environment variable, but saw that even with it set it looks for a forward slash 😅 , so thanks!
