### ISSUE TITLE
How can I draw a flaten brain map image

### ISSUE THREAD

**Issue by diaosilei** [Washington-University/workbench#56]
Recently, I have read some papers which have the illustrations just like the picture below. I try to find method to draw a picture like that using the data of dHCP, but I find noting. Could anyone tell me how I should do to transfer the 3-D data in dHCP to a 2-D illustration?
![illustration](https://user-images.githubusercontent.com/34775501/135717654-822a7073-6d7b-41f3-9931-b9d8f95f4618.png)

**Comment by glasserm** [comment]
This is not really a Workbench bug, but a more general question probably better posted on the HCP-Users mailing list.  Those are standard flattened surfaces upon which data can be displayed if it has been mapped to the standard 32k_fs_LR meshes.  This is done by default by the HCP Pipelines.  I don't know if dHCP does anything similar in their processing.

**Comment by diaosilei** [comment]
Thank you very much!











At 2021-10-02 23:46:27, "glasserm" ***@***.***> wrote:

This is not really a Workbench bug, but a more general question probably better posted on the HCP-Users mailing list. Those are standard flattened surfaces upon which data can be displayed if it has been mapped to the standard 32k_fs_LR meshes. This is done by default by the HCP Pipelines. I don't know if dHCP does anything similar in their processing.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
