### ISSUE TITLE
Identify two brain coordinates in two different colors 

### ISSUE THREAD

**Issue by reubebe** [Washington-University/workbench#70]
I am projecting TMS hotspot coordinates onto an inflated brain using the "Identify Brainordinate" window. The issue is, I am doing that with two groups and I want to identify the groups by color. But the window seems to allow only one kind of colour

**Comment by glasserm** [comment]
Perhaps Foci would be a better choice than ID nodes?

**Comment by reubebe** [comment]
I think foci worked fine. Thanks
