### ISSUE TITLE
How can I create my custom CIFTI label file, with particular ROIs, from another CIFTI label file?

### ISSUE THREAD

**Issue by Erfannaghavii** [Washington-University/workbench#72]
Hello everybody,
I wanted to merge some regions of interest (ROIs) in a CIFTI label file (for example, Myfile.dlabel.nii) from a previously established CIFTI label file (for example, Glasser.dlabel.nii). Let's imagine the original Glasser.dlabel.nii file has parcellated brain HCP resting-state fMRI data into 414 ROIs, but I want to merge regions 2, 213, and 400 into one region. Is there any particular way to do this in MATLAB using connectome workbench commands?
Thanks

**Comment by glasserm** [comment]
This sort of question is better asked on HCP-Users <hcp-users@humanconnectome.org> as it is not a bug or development issue with Connectome Workbench.
