### ISSUE TITLE
view limited to the right corner of the window when using wb_view (v2.0.0)

### ISSUE THREAD

**Issue by xuyangwen** [Washington-University/workbench#78]
I am using wb_view (v2.0.0) on the Mac OS. The view is limited to the small area in the right corner of the window (please see the attached picture). I do not know how to change it. Do you have any idea? Thank you!

<img width="1149" alt="Screenshot 2024-08-04 at 13 46 00" src="https://github.com/user-attachments/assets/b46e4566-b52c-4e3b-9a35-3fd2ff695a6c">

**Comment by glasserm** [comment]
what version of mac os?

**Comment by xuyangwen** [comment]
Sonoma 14.4.1

It shows the same problem on both my MacBook and Mac mini.

**Comment by xuyangwen** [comment]
To be more specific: the mac mini (Sonoma 14.4.1) and the macbook (Sonoma 14.5).
 They have the same problem.
